#!url=https://raw.githubusercontent.com/huskydsb/Shadowrocket/main/Sgmodule/test.module
#!name=Local Test Speed
#!desc=Local Streaming Speed Test
#!author=YourName
#!version=1.0
#!category=Test

[General]
force-http-engine-hosts = %APPEND% test.shadowrocket

[Script]
Rewrite: TestSpeed = type=http-request, pattern=^https?:\/\/test\.shadowrocket, script-path=https://raw.githubusercontent.com/huskydsb/Shadowrocket/main/Scripts/test.js, timeout=60

[MITM]
hostname = %INSERT% test.shadowrocket