#!name=ZIPPO 会员中心签到任务
#!desc=搜索"ZIPPO会员中心"小程序，登录后重新进入，点击"我的"，看到"数据获取成功"即可用脚本。
#!openUrl=https://www.zippo.com.cn/
#!author=Yuheng0101[https://github.com/Yuheng0101]
#!icon=https://raw.githubusercontent.com/Yuheng0101/X/main/Assets/zippo.jpg
#!arguments=启用Cookie获取:true, 签到任务时间:0 10 * * *, 启用签到任务:true
#!arguments-desc=\n★参数说明:\n\n - 启用Cookie获取: 是否启用获取 ZIPPO 授权 Cookie 功能（默认开启）\n\n - 签到任务时间: Cron 表达式（默认每天上午10点）\n\n - 启用签到任务: 是否启用定时签到任务（默认开启）\n\n\n★提示:\n\n - 搜索 ZIPPO 会员中心小程序，登录后点击“我的”确认数据获取成功\n - Cron 示例：每天 10:00 → `0 10 * * *`；每周一 12:00 → `0 12 * * 1`

[Script]

# ===== 获取 ZIPPO 会员中心授权 Cookie =====
ZIPPO获取Cookie = type=http-request, pattern=^https?:\/\/wx-center\.zippo\.com\.cn\/api\/users\/profile, requires-body=true, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/zippo.js, enable={{{启用Cookie获取}}}, timeout=120

# ===== ZIPPO 会员中心签到任务 =====
ZIPPO签到 = type=cron, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/zippo.js, cronexpr={{{签到任务时间}}}, timeout=10, enable={{{启用签到任务}}}

[MITM]
hostname = %APPEND% wx-center.zippo.com.cn