#!name = 京东京豆签到任务
#!desc = 打开京东我的页面查看京豆数量自动捕获 pt_key/pt_pin 并执行每日京豆签到。
#!openUrl = https://home.m.jd.com
#!icon = https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/task/jd.png
#!system = iOS
#!system_version = 26.1
#!loon_version = 3.2.4(787)
#!tag = 签到脚本

[Argument]

# 控制是否启用获取京东 Cookie 的脚本
enable-jd-cookie = switch, true, false, tag = 获取Cookie开关, desc = 是否启用通过拦截获取京东Cookie

# 设置签到的定时任务时间（默认每天 8 点）
cron-jd = input, "0 8 * * *", tag = 签到任务时间, desc = 定时任务表达式（例如每天07:00执行）

# 签到任务启用开关
Task-jd = switch, true, false, tag = 签到任务开关, desc = 定时运行[京东]签到任务

[Script]

# 捕获京东 Cookie（pt_key + pt_pin）
http-request ^https:\/\/api\.m\.jd\.com\/api\?functionId=bff_rightsCenter_jdInteractTask&scene=jdInteractTask script-path=https://raw.githubusercontent.com/huskydsb/Loon/main/Script/jdcookie.js, requires-body=false, enabled={enable-jd-cookie}, timeout=60, tag=京东获取Cookie, img-url=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/task/jd.png

# 京豆签到任务（每日签到）
cron {cron-jd} script-path=https://raw.githubusercontent.com/huskydsb/Loon/main/Script/jd.js, timeout=120, tag=京东签到, img-url=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/task/jd.png, enabled={Task-jd}

[Mitm]
hostname = api.m.jd.com