#!name=名创优品签到任务
#!desc=打开名创优品小程序自动获取 UID/SKEY 并执行名创优品每日签到任务。
#!openUrl=https://www.miniso.com
#!author=huskydsb[https://github.com/huskydsb]
#!icon=https://upload.wikimedia.org/wikipedia/commons/6/60/Miniso_logo.png
#!arguments=获取Cookie开关:true, 签到任务时间:0 8 * * *, 签到任务开关:true
#!arguments-desc=\n★ 获取Cookie开关：是否启用名创优品 Cookie 抓取（content-uid + content-skey）\n★ 签到任务时间：Cron 表达式（默认每天 08:00）\n★ 签到任务开关：是否启用名创优品每日签到任务
#!tag=签到脚本

[Script]

# ==========================
# 获取名创优品 Cookie
# ==========================

名创优品_获取Cookie = type=http-request, pattern=^https:\/\/member-center\.miniso\.com\/userinfo\/userinfo\/GetUserInfoV3$, script-path=https://raw.githubusercontent.com/huskydsb/Loon/main/Script/mcypcookie.js, requires-body=false, enable={{{获取Cookie开关}}}, timeout=60

# ==========================
# 名创优品签到任务（主任务）
# ==========================

名创优品_签到 = type=cron, script-path=https://raw.githubusercontent.com/huskydsb/Loon/main/Script/miniso.js, cronexpr={{{签到任务时间}}}, timeout=120, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% member-center.miniso.com
