#!name=托迈酷客签到任务
#!desc=每日签到可获得积分。进入“复游会”小程序自动获取 Cookie。Environment variable: ThomasCook_Cookie。
#!openUrl=https://www.thomascook.com.cn/
#!author=FoKit[https://github.com/FoKit]
#!icon=https://raw.githubusercontent.com/Sliverkiss/QuantumultX/main/icon/Tmkk.png
#!arguments=托迈酷客Cookie:"", 签到任务时间:0 8 * * *, 签到任务开关:true
#!arguments-desc=\n★ 托迈酷客Cookie：脚本使用的 Cookie，若留空则使用抓取到的 Cookie\n★ 签到任务时间：Cron 表达式（默认每天 08:00）\n★ 签到任务开关：是否开启每日签到任务
#!tag=签到脚本

[Script]

# ==========================
# 获取托迈酷客 Cookie
# ==========================

托迈酷客_获取Cookie = type=http-request, pattern=^https:\/\/apis\.folidaymall\.com\/online\/capi\/uc\/getCount$, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/ThomasCook.js, requires-body=false, enable=true, timeout=60

# ==========================
# 托迈酷客签到任务（主任务）
# ==========================

托迈酷客_签到 = type=cron, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/ThomasCook.js, cronexpr={{{签到任务时间}}}, timeout=120, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% apis.folidaymall.com
