#!name=携程旅行签到任务
#!desc=自动签到携程旅行并获取授权，需开启 Cookie 抓取脚本。
#!openUrl=https://m.ctrip.com
#!author=NobyDa[https://github.com/NobyDa]
#!icon=https://raw.githubusercontent.com/NobyDa/mini/master/Color/ctrip.png
#!arguments=获取Cookie开关:true, 签到任务时间:30 8 * * *, 签到任务开关:true
#!arguments-desc=\n★ 获取Cookie开关：是否启用获取携程旅行 Cookie\n★ 签到任务时间：Cron 表达式（默认每天 08:30）\n★ 签到任务开关：是否开启每日签到任务
#!tag=签到任务

[Script]

# ==========================
# 获取携程旅行 Cookie
# ==========================

携程旅行_获取Cookie = type=http-response, pattern=^https:\/\/m\.ctrip\.com\/restapi\/soa2\/\d+\/[a-zA-Z]+Login(?:$|\?), script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Ctrip-DailyBonus/Ctrip.js, requires-body=true, enable={{{获取Cookie开关}}}, timeout=60

# ==========================
# 携程旅行签到任务（主任务）
# ==========================

携程旅行_签到 = type=cron, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Ctrip-DailyBonus/Ctrip.js, cronexpr={{{签到任务时间}}}, timeout=60, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% m.ctrip.com
