#!name=新浪微博签到任务
#!desc=自动签到微博并获取 Cookie，支持定时签到与请求拦截。
#!openUrl=https://weibo.com
#!author=fmz200[https://github.com/fmz200]
#!icon=https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Weibo-00.png
#!arguments=获取Cookie开关:true, 签到任务时间:5 0 * * *, 签到任务开关:true
#!arguments-desc=\n★ 获取Cookie开关：是否启用微博 Cookie 抓取\n★ 签到任务时间：Cron 表达式（默认每天 00:05）\n★ 签到任务开关：是否开启每日签到任务
#!tag=签到脚本

[Script]

# ==========================
# 获取新浪微博 Cookie
# ==========================

新浪微博_获取Cookie = type=http-request, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/\d\/users\/show$, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/cookie/get_cookie.js, requires-body=false, enable={{{获取Cookie开关}}}, timeout=60

# ==========================
# 新浪微博签到任务（主任务）
# ==========================

新浪微博_签到 = type=cron, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_signin.js, cronexpr={{{签到任务时间}}}, timeout=120, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% api.weibo.cn, weibo.com, weibo.cn