#!name=日清食品体验馆签到任务
#!desc=自动获取日清食品体验馆参数并执行签到（若脚本支持）。访问页面触发拦截以获取 token/参数。
#!openUrl=https://www.cupnoodles-museum.jp/zh-cn/yokohama/about/
#!author=xzxxn777[https://github.com/xzxxn777]
#!icon=https://raw.githubusercontent.com/sliverkiss/QuantumultX/main/icon/rqsp.png
#!arguments=获取Token开关:true, 签到任务时间:0 8 * * *, 签到任务开关:true
#!arguments-desc=\n★ 获取Token开关：是否启用拦截并保存日清参数/CK\n★ 签到任务时间：Cron 表达式（默认每天 08:00）\n★ 签到任务开关：是否启用日清食品体验馆签到任务
#!tag=签到脚本

[Script]

# ==========================
# 获取日清 token
# ==========================

日清食品体验馆_获取Token = type=http-response, pattern=^https:\/\/prod-api\.nissinfoodium\.com\.cn\/gw-shop\/app\/v1\/user\/detail$, script-path=https://raw.githubusercontent.com/xzxxn777/Surge/main/Script/RQSP/RQSP.js, requires-body=1, max-size=0, enable={{{获取Token开关}}}, timeout=60

# ==========================
# 日清食品体验馆签到任务（主任务）
# ==========================

日清食品体验馆_签到 = type=cron, script-path=https://raw.githubusercontent.com/xzxxn777/Surge/main/Script/RQSP/RQSP.js, cronexpr={{{签到任务时间}}}, timeout=3600, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% prod-api.nissinfoodium.com.cn
