#!name=晓晓优选签到任务
#!desc=晓晓优选（晓晓霸王餐）签到任务。进入小程序“我的”页自动获取 CK。
#!openUrl=https://xiaoxiaoyouxuan.com
#!author=Sliverkiss[https://github.com/Sliverkiss]
#!icon=https://raw.githubusercontent.com/sliverkiss/QuantumultX/main/icon/xxyx.png
#!arguments=获取Token开关:true, 签到任务时间:0 8 * * *, 签到任务开关:true
#!arguments-desc=\n★ 获取Token开关：是否启用拦截并保存晓晓优选 CK\n★ 签到任务时间：Cron 表达式（默认每天 08:00）\n★ 签到任务开关：是否启用每日签到任务
#!tag=签到脚本

[Script]

# ==========================
# 获取晓晓优选 CK
# ==========================

晓晓优选_获取CK = type=http-response, pattern=^https:\/\/xxyx-client-api\.xiaoxiaoyouxuan\.com\/my$, script-path=https://gist.githubusercontent.com/Sliverkiss/991a81be1fc8cf2a1937432be68f5521/raw/xxyx.js, requires-body=true, enable={{{获取Token开关}}}, timeout=60

# ==========================
# 晓晓优选签到任务（主任务）
# ==========================

晓晓优选_签到 = type=cron, script-path=https://gist.githubusercontent.com/Sliverkiss/991a81be1fc8cf2a1937432be68f5521/raw/xxyx.js, cronexpr={{{签到任务时间}}}, timeout=120, enable={{{签到任务开关}}}

[MITM]
hostname = %APPEND% xxyx-client-api.xiaoxiaoyouxuan.com
