#!name=鸿星尔克签到任务
#!desc=自动执行鸿星尔克签到脚本。配置定时任务后，到点自动签到。
#!openUrl=https://www.hxek.com
#!author=Sliverkiss[https://github.com/Sliverkiss]
#!icon=https://raw.githubusercontent.com/Sliverkiss/QuantumultX/main/icon/Hxek.png
#!arguments=获取Cookie开关:true, 签到任务时间:0 8 * * *, 鸿星尔克签到任务:true
#!arguments-desc=\n★ 获取Cookie开关：是否启用自动抓取鸿星尔克 Cookie\n★ 签到任务时间：Cron 表达式（默认每天 8:00）\n★ 鸿星尔克签到任务：是否启用定时签到任务
#!tag=签到脚本

[Script]

# ==========================
# 鸿星尔克 - 获取 Cookie
# ==========================
鸿星尔克_获取Cookie = type=http-request, pattern=^https:\/\/hope\.demogic\.com\/gic-wx-app\/get-member-asset\.json, script-path=https://raw.githubusercontent.com/Former-Years/Surge/refs/heads/main/Script/erke.js, enable={{{获取Cookie开关}}}
# ==========================
# 鸿星尔克 - 定时签到任务
# ==========================
鸿星尔克_签到 = type=cron, script-path=https://raw.githubusercontent.com/Sliverkiss/GoodNight/master/Script/hxek.js, cronexpr={{{签到任务时间}}}, timeout=120, enable={{{鸿星尔克签到任务}}}

[MITM]
hostname = %APPEND% hope.demogic.com